/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.google.common.collect.Table;
import org.junit.Test;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.channels.FileChannel;
import java.util.Set;

public class AppTest {
    private static final String WIKI_ARTICLES_FILE_PATH = "C:\\Users\\MehmetEminMumcu\\Desktop\\memn\\hacettepe\\cmp614\\assignment2\\cmp614-assignment2\\src\\main\\resources\\assign2.articles";
    private static final String TEST_ARTICLES_FILE_PATH = "C:\\Users\\MehmetEminMumcu\\Desktop\\memn\\hacettepe\\cmp614\\assignment2\\cmp614-assignment2\\src\\main\\resources\\assign2Test.articles";
    private static final double TEST_FILE_DOCUMENT_FACTOR = 0.1;

    //@Test
    @SuppressWarnings("unused")
    public void buildTestFile() throws Exception {

        File testFile = new File(TEST_ARTICLES_FILE_PATH);
        File source = new File(WIKI_ARTICLES_FILE_PATH);

        try (FileChannel inputChannel = new FileInputStream(source).getChannel();
             FileChannel outputChannel = new FileOutputStream(testFile).getChannel()) {
            outputChannel.transferFrom(inputChannel, 0,
                    (long) (inputChannel.size() * TEST_FILE_DOCUMENT_FACTOR));
        }
    }

    @Test
    public void testBuildVocabulary() throws Exception {

        App app = new App();
        Set<String> vocabulary = app.buildVocabulary(TEST_ARTICLES_FILE_PATH);
        System.out.println("vocab size: " + vocabulary.size());

    }

    @Test
    public void testBuildDocumentTermMatrix() throws Exception {
        App app = new App();
        Table<String, Long, Long> documentTermMatrix = app.buildTermDocumentMatrix(TEST_ARTICLES_FILE_PATH);
        System.out.println("vocabulary size: " + documentTermMatrix.rowKeySet().size());
        System.out.println("document size: " + documentTermMatrix.columnKeySet().size());
    }
}
